# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload executable jar file to upload-release
# for more details see https://github.com/marketplace/actions/upload-files-to-a-github-release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/gsxconfig-1.0-SNAPSHOT.jar
        asset_name: gsxconfig.jar
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is an executable jar file" 

